version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm run dev"
    ports:
      - "8000:3000"

  backend:
    tty: true
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: "/app"
    command: "rails server -b 0.0.0.0 -p 3000"
    depends_on:
      - db
    stdin_open: true

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - 4306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  db-store: