import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useAuthContext } from '../services/firebase/AuthContext';
import { Button } from '@mui/material';

export default function Home() {
  const { user } = useAuthContext();

  // 認証テスト
  const setConfig =async () => {
    const token = await user?.getIdToken();
    const config = {
      headers: { authorization: `Bearer ${token}` },
    };
    return config;
  };

  const onClickButton = async () => {
    const config = await setConfig();
    console.log("clicked", config);
    await axios.get(`http://localhost:3000/api/v1/users`, {
      params: {
        uid: user?.uid
      },
    })
      .then((res) => {
        console.log(res);
      })
      .catch((error) => {
        console.log(error);
      });
  };

  return (
    <>
      <Head>
        <title>Pet Photo SNS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World</h1>
        <Button onClick={onClickButton}>Get hello</Button>
      </main>
    </>
  );
};
