import Head from "next/head";
import Grid from "@mui/material/Grid";
import PostCard from "../components/PostCard";
import { postList } from "../lib/postApiClient";
import Link from 'next/link';

export async function getServerSideProps() {
  const posts = await postList.get("/");
  return {
    props: {
      posts: posts.data,
    },
  };
}

export default function Home(props:any) {
  const posts = props.posts;

  return (
    <>
      <Head>
        <title>Pet Photo SNS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid container rowSpacing={3} columnSpacing={3} mt={10} justifyContent="center">
          {posts.map((post:any) => {
            return <PostCard key={post.id} post={post}/>;
          })}
        </Grid>
      </main>
    </>
  );
}
